# Generated by Django 4.0.1 on 2022-04-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folha',
            fields=[
                ('id_folha', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('anomes', models.IntegerField(null=True)),
                ('codigo', models.IntegerField(null=True)),
                ('nome_servidor', models.CharField(max_length=100, null=True)),
                ('carga_horaria', models.IntegerField(null=True)),
                ('cpf', models.CharField(max_length=15, null=True)),
                ('secretaria', models.CharField(max_length=100, null=True)),
                ('setor', models.CharField(max_length=100, null=True)),
                ('tipo_admissao', models.CharField(max_length=100, null=True)),
                ('data_admissao', models.CharField(max_length=10, null=True)),
                ('previdencia', models.CharField(max_length=100, null=True)),
                ('funcao', models.CharField(max_length=100, null=True)),
                ('tipo', models.IntegerField(null=True)),
                ('evento', models.CharField(max_length=100, null=True)),
                ('ref_evento', models.CharField(max_length=20, null=True)),
                ('valor_evento', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('classificacao', models.CharField(max_length=15, null=True)),
                ('cod_evento', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'folhas',
            },
        ),
        migrations.AddIndex(
            model_name='folha',
            index=models.Index(fields=['id_municipio', 'anomes', 'codigo'], name='folhas_id_muni_4cceab_idx'),
        ),
    ]
