# Generated by Django 4.0.1 on 2022-04-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupo_eventos',
        ),
        migrations.DeleteModel(
            name='Grupo_funcoes',
        ),
    ]
