# Generated by Django 4.0.1 on 2022-04-11 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventos_cv',
        ),
    ]
