# Generated by Django 4.0.1 on 2022-03-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cl_orcamentaria',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
