# Generated by Django 4.0.1 on 2022-04-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_delete_eventos_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos_cv',
            fields=[
                ('id_evento_cv', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=100)),
                ('tipo', models.CharField(default='V', max_length=1)),
                ('cancelado', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'eventos_cv',
            },
        ),
    ]
