# Generated by Django 4.0.1 on 2022-04-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_delete_grupo_eventos_delete_grupo_funcoes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='funcao',
            name='unique_funcao',
        ),
    ]
