# Generated by Django 4.0.1 on 2022-05-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_folha_folha_folhas_id_muni_4cceab_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id_complemento', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('anomes', models.IntegerField(null=True)),
                ('codigo', models.IntegerField(null=True)),
                ('ref_evento', models.CharField(default='', max_length=20, null=True)),
            ],
            options={
                'db_table': 'complementos',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('anomes', models.IntegerField(null=True)),
                ('codigo', models.IntegerField(null=True)),
                ('nome_servidor', models.CharField(max_length=100, null=True)),
                ('carga_horaria', models.IntegerField(null=True)),
                ('secretaria', models.CharField(max_length=100, null=True)),
                ('setor', models.CharField(max_length=100, null=True)),
                ('tipo_admissao', models.CharField(max_length=100, null=True)),
                ('data_admissao', models.CharField(max_length=10, null=True)),
                ('previdencia', models.CharField(max_length=100, null=True)),
                ('funcao', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Provento',
            fields=[
                ('id_provento', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('anomes', models.IntegerField(null=True)),
                ('codigo', models.IntegerField(null=True)),
                ('previdencia', models.CharField(default='', max_length=100, null=True)),
                ('tipo', models.IntegerField(null=True)),
                ('evento', models.CharField(max_length=100, null=True)),
                ('valor_evento', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('classificacao', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'proventos',
            },
        ),
        migrations.AddIndex(
            model_name='provento',
            index=models.Index(fields=['id_municipio', 'anomes', 'codigo'], name='proventos_id_muni_ea111b_idx'),
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['id_municipio', 'anomes', 'codigo'], name='funcionario_id_muni_602431_idx'),
        ),
        migrations.AddIndex(
            model_name='complemento',
            index=models.Index(fields=['id_municipio', 'anomes', 'codigo'], name='complemento_id_muni_352868_idx'),
        ),
    ]
