# Generated by Django 4.0.1 on 2022-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_delete_grupo_eventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo_eventos',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=50, null=True)),
                ('evento_original', models.CharField(max_length=100, null=True)),
                ('evento_principal', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'grupo_eventos',
            },
        ),
        migrations.AddConstraint(
            model_name='grupo_eventos',
            constraint=models.UniqueConstraint(fields=('empresa', 'evento_original'), name='unique_grupo_eventos'),
        ),
    ]
