# Generated by Django 4.0.1 on 2022-04-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_eventos_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcao',
        ),
    ]
