# Generated by Django 4.0.1 on 2022-04-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_grupo_eventos_grupo_eventos_unique_grupo_eventos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcao',
        ),
        migrations.DeleteModel(
            name='Grupo_funcoes',
        ),
    ]
