# Generated by Django 4.0.1 on 2022-06-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_complemento_funcionario_provento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provento',
            name='grupamento',
            field=models.CharField(default='N', max_length=1, null=True),
        ),
    ]
