# Generated by Django 4.0.1 on 2022-04-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_delete_funcao_delete_grupo_funcoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id_funcao', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(default='', max_length=50)),
                ('funcao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'funcoes',
            },
        ),
        migrations.CreateModel(
            name='Grupo_funcoes',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=50, null=True)),
                ('funcao_original', models.CharField(max_length=100, null=True)),
                ('funcao_principal', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'grupo_funcoes',
            },
        ),
        migrations.AddConstraint(
            model_name='grupo_funcoes',
            constraint=models.UniqueConstraint(fields=('empresa', 'funcao_original'), name='unique_grupo_funcoes'),
        ),
        migrations.AddConstraint(
            model_name='funcao',
            constraint=models.UniqueConstraint(fields=('empresa', 'funcao'), name='unique_funcao'),
        ),
    ]
