# Generated by Django 4.0.1 on 2022-03-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_planilha_planilha_planilhas_codigo_72556f_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planilha',
        ),
    ]
