# Generated by Django 4.0.1 on 2022-07-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_delete_folha_delete_planilha_provento_lixo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folhames',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='folhames',
            name='data_criacao',
            field=models.DateTimeField(null=True),
        ),
    ]
