# Generated by Django 4.0.1 on 2022-04-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_funcao_grupo_funcoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos_cv',
            fields=[
                ('id_evento_cv', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=100)),
                ('cancelado', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'eventos_cv',
            },
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='exibe_excel',
            new_name='id_evento_cv',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='ordenacao',
        ),
        migrations.AlterField(
            model_name='evento',
            name='evento',
            field=models.CharField(max_length=100),
        ),
    ]
