# Generated by Django 4.0.1 on 2022-04-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_funcao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcao',
        ),
        migrations.DeleteModel(
            name='Funcoes_cv',
        ),
    ]
