# Generated by Django 4.0.1 on 2022-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_delete_planilha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planilha',
            fields=[
                ('id_planilha', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(null=True)),
                ('data_ref', models.DateField()),
                ('codigo_folha', models.IntegerField(null=True)),
                ('folha', models.CharField(max_length=100, null=True)),
                ('nome_servidor', models.CharField(max_length=100, null=True)),
                ('carga_horaria', models.IntegerField(null=True)),
                ('cpf', models.CharField(max_length=15, null=True)),
                ('secretaria', models.CharField(max_length=100, null=True)),
                ('setor', models.CharField(max_length=100, null=True)),
                ('tipo_admissao', models.CharField(max_length=100, null=True)),
                ('previdencia', models.CharField(max_length=100, null=True)),
                ('vinculo', models.CharField(max_length=100, null=True)),
                ('funcao', models.CharField(max_length=100, null=True)),
                ('lotacao', models.CharField(max_length=100, null=True)),
                ('entidade', models.CharField(max_length=100, null=True)),
                ('tipo', models.IntegerField(null=True)),
                ('evento', models.CharField(max_length=100, null=True)),
                ('ref_evento', models.CharField(max_length=20, null=True)),
                ('valor_evento', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('classificacao', models.CharField(max_length=15, null=True)),
                ('cargo', models.CharField(max_length=50, null=True)),
                ('cod_evento', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'nome_servidor',
            },
        ),
        migrations.AddIndex(
            model_name='planilha',
            index=models.Index(fields=['codigo'], name='nome_servid_codigo_ae9c16_idx'),
        ),
    ]
