# Generated by Django 4.0.1 on 2022-04-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_delete_funcao_delete_funcoes_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id_funcao', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('empresa', models.CharField(default='', max_length=50)),
                ('funcao', models.CharField(max_length=100)),
                ('id_funcao_cv', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'funcoes',
            },
        ),
    ]
