# Generated by Django 4.0.1 on 2022-04-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_eventos_cv_rename_exibe_excel_evento_id_evento_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='evento',
            field=models.CharField(max_length=50),
        ),
    ]
