# Generated by Django 4.0.1 on 2022-03-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_planilha_planilha_nome_servid_codigo_ae9c16_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planilha',
        ),
    ]
