# Generated by Django 4.0.1 on 2022-04-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_funcao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Eventos_cv',
        ),
        migrations.DeleteModel(
            name='Funcao',
        ),
    ]
