# Generated by Django 4.0.1 on 2022-04-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_evento_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventos_cv',
        ),
    ]
