# Generated by Django 4.0.1 on 2022-04-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_delete_eventos_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos_cv',
            fields=[
                ('id_evento_cv', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=100)),
                ('cancelado', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'eventos_cv',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='exibe_excel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evento',
            name='ordenacao',
            field=models.IntegerField(default=0),
        ),
    ]
