# Generated by Django 4.0.1 on 2022-04-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_delete_evento_delete_eventos_cv_delete_funcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('empresa', models.CharField(default='', max_length=50)),
                ('tipo', models.CharField(choices=[('', ''), ('V', 'VANTAGEM'), ('D', 'DESCONTO')], default='V', max_length=9)),
                ('evento', models.CharField(max_length=50)),
                ('cancelado', models.CharField(default='N', max_length=1)),
                ('exibe_excel', models.IntegerField(default=1)),
                ('ordenacao', models.IntegerField(default=0)),
                ('cl_orcamentaria', models.CharField(max_length=6, null=True)),
                ('id_evento_cv', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id_funcao', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('empresa', models.CharField(default='', max_length=50)),
                ('funcao', models.CharField(max_length=100)),
                ('id_funcao_cv', models.IntegerField(default=0)),
                ('cancelado', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'funcoes',
            },
        ),
    ]
