# Generated by Django 4.0.1 on 2022-03-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_delete_planilha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planilha',
            fields=[
                ('id_planilha', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('data_ref', models.DateField()),
                ('codigo_folha', models.IntegerField()),
                ('folha', models.CharField(max_length=100)),
                ('nome_servidor', models.CharField(max_length=100, null=True)),
                ('carga_horaria', models.IntegerField(null=True)),
                ('cpf', models.CharField(max_length=15, null=True)),
                ('secretaria', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('tipo_admissao', models.CharField(max_length=100)),
                ('previdencia', models.CharField(max_length=100, null=True)),
                ('funcao', models.CharField(max_length=100)),
                ('lotacao', models.CharField(max_length=100)),
                ('entidade', models.CharField(max_length=100)),
                ('tipo', models.IntegerField()),
                ('evento', models.CharField(max_length=100)),
                ('ref_evento', models.CharField(max_length=20)),
                ('valor_evento', models.DecimalField(decimal_places=2, max_digits=9)),
                ('classificacao', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=50, null=True)),
                ('cod_evento', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'planilhas',
            },
        ),
        migrations.AddIndex(
            model_name='planilha',
            index=models.Index(fields=['codigo'], name='planilhas_codigo_72556f_idx'),
        ),
    ]
