# Generated by Django 4.0.1 on 2022-03-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_planilha_planilha_planilhas_codigo_72556f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilha',
            name='data_admissao',
            field=models.DateField(default=None, null=True),
        ),
    ]
