# Generated by Django 4.0.1 on 2022-03-24 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_planilha_data_admissao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planilha',
        ),
    ]
