# Generated by Django 4.0.1 on 2022-03-30 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_planilha_planilha_planilhas_codigo_72556f_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folhaevento',
        ),
        migrations.DeleteModel(
            name='Folhames',
        ),
        migrations.DeleteModel(
            name='Servidor',
        ),
    ]
