# Generated by Django 4.0.1 on 2022-03-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_delete_folhaevento_delete_folhames_delete_servidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folhaevento',
            fields=[
                ('id_folhaevento', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('anomes', models.IntegerField()),
                ('cod_servidor', models.IntegerField()),
                ('previdencia', models.CharField(max_length=6, null=True)),
                ('cl_orcamentaria', models.CharField(max_length=6, null=True)),
                ('id_evento', models.IntegerField(null=True)),
                ('tipo', models.CharField(max_length=1, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'folhaeventos',
            },
        ),
        migrations.CreateModel(
            name='Folhames',
            fields=[
                ('id_folha', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('anomes', models.IntegerField()),
                ('cod_servidor', models.IntegerField()),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('id_secretaria', models.IntegerField(null=True)),
                ('id_setor', models.IntegerField(null=True)),
                ('id_funcao', models.IntegerField(null=True)),
                ('id_vinculo', models.IntegerField(null=True)),
                ('previdencia', models.CharField(max_length=6, null=True)),
                ('carga_horaria', models.IntegerField(null=True)),
                ('dias', models.CharField(max_length=30, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'folhames',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id_servidor', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('cod_servidor', models.IntegerField()),
                ('cpf', models.CharField(default='', max_length=20)),
                ('data_admissao', models.DateField(null=True)),
                ('ativo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'servidores',
            },
        ),
        migrations.AddIndex(
            model_name='servidor',
            index=models.Index(fields=['id_municipio'], name='servidores_id_muni_9234b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'cod_servidor'), name='servidor_unique'),
        ),
        migrations.AddIndex(
            model_name='folhames',
            index=models.Index(fields=['id_municipio', 'anomes'], name='folhames_id_muni_e88aea_idx'),
        ),
        migrations.AddIndex(
            model_name='folhaevento',
            index=models.Index(fields=['id_municipio', 'anomes'], name='folhaevento_id_muni_ef07fe_idx'),
        ),
    ]
