# Generated by Django 4.0.1 on 2022-03-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_folhaevento_folhames_servidor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refeventos',
            fields=[
                ('id_ref', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('anomes', models.IntegerField()),
                ('cod_servidor', models.IntegerField()),
                ('ref_eventos', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'refeventos',
            },
        ),
        migrations.DeleteModel(
            name='Folha',
        ),
        migrations.AddConstraint(
            model_name='refeventos',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'anomes', 'cod_servidor'), name='unique_refeventos'),
        ),
    ]
