# Generated by Django 4.0.1 on 2022-03-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_refeventos_delete_folha_refeventos_unique_refeventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo_funcoes',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('desc_funcao', models.CharField(max_length=100, null=True)),
                ('desc_funcao_principal', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'grupo_funcoes',
            },
        ),
        migrations.AddConstraint(
            model_name='grupo_funcoes',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'desc_funcao'), name='unique_grupo_funcoes'),
        ),
    ]
