# Generated by Django 4.0.1 on 2022-03-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_grupo_eventos_grupo_eventos_unique_grupo_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ref_evento',
            field=models.IntegerField(default=0),
        ),
    ]
