# Generated by Django 4.0.1 on 2022-04-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_evento_ref_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='ref_evento',
            new_name='exibe_excel',
        ),
    ]
