# Generated by Django 4.0.1 on 2022-04-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_rename_ref_evento_evento_exibe_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo_eventos',
            name='id_user',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='grupo_eventos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
