# Generated by Django 4.0.1 on 2022-04-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_grupo_eventos_id_user_grupo_eventos_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo_funcoes',
            name='id_user',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='grupo_funcoes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
