# Generated by Django 4.0.1 on 2022-04-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_remove_grupo_eventos_unique_grupo_eventos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='string_pesquisa',
            new_name='empresa',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='modelo',
        ),
        migrations.AddField(
            model_name='municipio',
            name='entidade',
            field=models.CharField(default='', max_length=100),
        ),
    ]
