# Generated by Django 4.0.1 on 2022-04-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_alter_evento_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo_eventos',
            name='empresa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
