# Generated by Django 4.0.1 on 2022-04-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0026_alter_grupo_eventos_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cancelado',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
