# Generated by Django 4.0.1 on 2022-04-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_evento_cancelado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grupo_eventos',
            name='unique_grupo_eventos',
        ),
        migrations.RenameField(
            model_name='grupo_eventos',
            old_name='desc_evento',
            new_name='evento_original',
        ),
        migrations.RenameField(
            model_name='grupo_eventos',
            old_name='desc_evento_principal',
            new_name='evento_principal',
        ),
        migrations.AddConstraint(
            model_name='grupo_eventos',
            constraint=models.UniqueConstraint(fields=('empresa', 'evento_original'), name='unique_grupo_eventos'),
        ),
    ]
