# Generated by Django 4.0.1 on 2022-04-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_remove_grupo_eventos_unique_grupo_eventos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='id_municipio',
        ),
    ]
