# Generated by Django 4.0.1 on 2022-04-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0029_remove_evento_codigo_remove_evento_id_municipio'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evento',
            name='evento_unique',
        ),
        migrations.RemoveField(
            model_name='grupo_eventos',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='grupo_eventos',
            name='updated_at',
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.UniqueConstraint(fields=('empresa', 'evento'), name='evento_unique'),
        ),
    ]
