# -*- coding: utf-8 -*-



MUNICIPIOS_CHOICES = [
   {'id':150,'name':'Abaiara'},
   {'id':129,'name':'Acarape'},
   {'id':1, 'name':'Caridade'},
   {'id':76, 'name':'Independência'},     
   {'id':153,'name':'Ipaporanga'}]


ID_MUNICIPIOS_CHOICES = [
        (150,'Abaiara'),
        (129,'Acarape'),
        (24,'Acaraú'),
        (33,'Acopiara'),
        (117,'Aiuaba'),
        (151,'Alcântaras'),
        (173,'Altaneira'),
        (125,'Alto Santo'),
        (41,'Amontada'),
        (175,'Antonina do Norte'),
        (131,'Apuiarés'),
        (13,'Aquiraz'),
        (17,'Aracati'),
        (73,'Aracoiaba'),
        (160,'Ararendá'),
        (93,'Araripe'),
        (152,'Aratuba'),
        (169,'Arneiroz'),
        (84,'Assaré'),
        (82,'Aurora'),
        (179,'Baixio'),
        (110,'Banabuiú'),
        (26,'Barbalha'),
        (89,'Barreira'),
        (87,'Barro'),
        (130,'Barroquinha'),
        (53,'Baturité'),
        (35,'Beberibe'),
        (60,'Bela Cruz'),
        (34,'Boa Viagem'),
        (37,'Brejo Santo'),
        (23,'Camocim'),
        (69,'Campos Sales'),
        (15,'Canindé'),
        (114,'Capistrano'),
        (86,'Caridade'),
        (108,'Cariré'),
        (72,'Caririaçu'),
        (106,'Cariús'),
        (115,'Carnaubal'),
        (20,'Cascavel'),
        (96,'Catarina'),
        (161,'Catunda'),
        (2,'Caucaia'),
        (143,'Chaval'),
        (139,'Choró'),
        (100,'Chorozinho'),
        (85,'Coreaú'),
        (18,'Crateús'),
        (6,'Crato'),
        (112,'Croatá'),
        (79,'Cruz'),
        (176,'Ereré'),
        (32,'Eusébio'),
        (81,'Forquilha'),
        (1,'Fortaleza'),
        (120,'Fortim'),
        (136,'Frecheirinha'),
        (170,'General Sampaio'),
        (134,'Graça'),
        (31,'Granja'),
        (181,'Granjeiro'),
        (156,'Groaíras'),
        (74,'Guaiúba'),
        (48,'Guaraciaba do Norte'),
        (180,'Guaramiranga'),
        (102,'Hidrolândia'),
        (21,'Horizonte'),
        (141,'Ibaretama'),
        (78,'Ibiapina'),
        (145,'Ibicuitinga'),
        (101,'Icapuí'),
        (22,'Icó'),
        (9,'Iguatu'),
        (76,'Independência'),
        (153,'Ipaporanga'),
        (146,'Ipaumirim'),
        (46,'Ipu'),
        (51,'Ipueiras'),
        (135,'Iracema'),
        (162,'Irapuan Pinheiro'),
        (83,'Irauçuba'),
        (168,'Itaiçaba'),
        (50,'Itaitinga'),
        (36,'Itapajé'),
        (7,'Itapipoca'),
        (98,'Itapiúna'),
        (45,'Itarema'),
        (92,'Itatira'),
        (113,'Jaguaretama'),
        (154,'Jaguaribara'),
        (57,'Jaguaribe'),
        (58,'Jaguaruana'),
        (71,'Jardim'),
        (167,'Jati'),
        (99,'Jericoacoara'),
        (3,'Juazeiro do Norte'),
        (80,'Jucás'),
        (28,'Limoeiro do Norte'),
        (103,'Madalena'),
        (64,'Mangabeira'),
        (4,'Maracanaú'),
        (8,'Maranguape'),
        (68,'Marco'),
        (155,'Martinópole'),
        (49,'Massapê.jpg Massapê'),
        (39,'Mauriti'),
        (128,'Meruoca'),
        (70,'Milagres'),
        (142,'Milhã'),
        (138,'Miraíma'),
        (54,'Missão Velha'),
        (42,'Mombaça'),
        (27,'Morada Nova'),
        (165,'Moraújo'),
        (88,'Morrinhos'),
        (133,'Mucambo'),
        (158,'Mulungu'),
        (126,'Nova Olinda'),
        (62,'Nova Russas'),
        (67,'Novo Oriente'),
        (94,'Orós'),
        (19,'Pacajus'),
        (11,'Pacatuba'),
        (148,'Pacoti'),
        (177,'Pacujá'),
        (163,'Palhano'),
        (140,'Palmácia'),
        (55,'Paracuru'),
        (59,'Paraipaba'),
        (65,'Parambu'),
        (149,'Paramoti'),
        (44,'Pedra Branca'),
        (164,'Penaforte'),
        (52,'Pentecoste'),
        (123,'Pereiro'),
        (97,'Pindoretama'),
        (119,'Piquet Caneiro'),
        (159,'Pires Ferreira'),
        (147,'Poranga'),
        (132,'Porteiras'),
        (157,'Potengi'),
        (178,'Potiretama'),
        (95,'Quiterianópolis'),
        (10,'Quixadá'),
        (124,'Quixelô'),
        (12,'Quixeramobim'),
        (90,'Quixeré'),
        (66,'Redenção'),
        (111,'Reriutaba'),
        (14,'Russas'),
        (127,'Saboeiro'),
        (121,'Salitre'),
        (61,'Santana do Acaraú'),
        (116,'Santana do Cariri'),
        (43,'Santa Quitéria'),
        (40,'São Benedito'),
        (38,'São Gonçalo do Amarante'),
        (174,'São João do Jaguaribe'),
        (144,'São Luís do Curu'),
        (77,'Senador Pompeu'),
        (171,'Senador Sá'),
        (5,'Sobral'),
        (109,'Solonópole'),
        (118,'Tabosa'),
        (63,'Tabuleiro do Norte'),
        (75,'Tamboril'),
        (166,'Tarrafas'),
        (29,'Tauá'),
        (105,'Tejuçuoca'),
        (16,'Tianguá'),
        (30,'Trairi'),
        (122,'Tururu'),
        (56,'Ubajara'),
        (172,'Umari'),
        (104,'Umirim'),
        (91,'Uruburetama'),
        (137,'Uruoca'),
        (107,'Varjota'),
        (47,'Várzea Alegre'),
        (25,'Viçosa do Ceará'),
    ]


